### ISSUE TITLE
Issue with blank object ID

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-etl#29]
```
terraform plan -var-file=azure.secrets
╷
│ Error: expected "object_id" to be a valid UUID, got 
│ 
│   with module.secrets.azurerm_key_vault_access_policy.allow_user,
│   on secrets/keyvault.tf line 32, in resource "azurerm_key_vault_access_policy" "allow_user":
│   32:   object_id          = data.azurerm_client_config.current.object_id
```

**Comment by jemrobinson** [comment]
`data.azurerm_client_config.current.object_id` should give the object ID of your Azure user. See [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/client_config) for the docs.

**Comment by JimCircadian** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/17039 -> https://github.com/hashicorp/terraform-provider-azurerm/issues/16982

**Comment by JimCircadian** [comment]
Closed thanks to updated provider
