### ISSUE TITLE
Allow non-default organisation tenancy when setting up terraform

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet-etl#51]
Currently, when running `setup_terraform.py`, it authenticates the user on Azure via the browser, when it does so, it defaults to the organisation's tenancy. 

If the user has access to multiple tenancies, and the subscription the user wants to use is under one of the non-default tenancies, the user should be able to define which tenancy to use.

For example, when using BAS email to authenticate Azure, it defaults to the NERC tenancy, giving the following error:

```bash
$ ./setup_terraform.py -v -i [[REDACTED]] -s "Polar Forecasting and IceNet applications" -e $ICENET_AZENVIRONMENT -rg rg-icenet-$ICENET_AZENVIRONMENT -sa icenet$ICENET_AZENVIRONMENT -sc blob-icenet-${ICENET_AZENVIRONMENT}-terraform [[REDACTED]] [[REDACTED]]

2024-09-18 17:03:44     INFO: Successfully authenticated using: InteractiveBrowserCredential
Traceback (most recent call last):
  File "/home/bryald/git/icenet/icenet-etl/./simple_setup_terraform.py", line 176, in <module>
    main()
  File "/home/bryald/git/icenet/icenet-etl/./simple_setup_terraform.py", line 172, in main
    subscription_id, tenant_id = get_azure_ids(credential, args.azure_subscription_name)
  File "/home/bryald/git/icenet/icenet-etl/./simple_setup_terraform.py", line 63, in get_azure_ids
    return (subscription_id, tenant_id)
UnboundLocalError: local variable 'subscription_id' referenced before assignment
```

This is because the subscription I'm looking for is under the Turing tenancy.

**Comment by odoyhaha** [comment]
maybe this will help
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
